### ISSUE TITLE
Wrong behavior of $DELETE and modifying DynamoDB maps

### ISSUE THREAD

**Issue by dolsem** [dynamoosejs/dynamoose#398] opened 2018-07-30 04:12 UTC
I did some testing and found that updating with $ADD works as expected, i.e. I was able to successfully append an element to a list of type `[String]` by running:
```es6
Test.update(
  { id: 1 },
  { $ADD:
    { myList: ['new-item'] } 
  }
);
```
Next I tried deleting that element by changing `$ADD` to `$DELETE` in the above call. That call, however, deleted the whole attribute `myList`, not just the item. This behavior is different from `DELETE` in DynamoDB Update Expressions, [as you can see here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.DELETE).

`$DELETE` also deletes a counter instead of decrementing it, though I am not sure if that's different from Update Expressions behavior. I think it makes sense to have an expression that reverses the effect of `$ADD`. `$REMOVE`, perhaps?

Also, `$ADD` does not add a key-value pair to a DynamoDB map. With Update Expressions you can do it by using `SET`, [you can see an example here](https://stackoverflow.com/a/31149265/8207842). It would be very useful to be able to add and remove items from a map with Dynamoose. I suggest updating `$ADD` to support this and adding `$REMOVE` as an opposite of `$ADD`. If you think it makes sense, I might submit a PR, though it might take a while, cause my time is very limited.

**Comment by fishcharlie** [comment] 2018-07-30 17:57
@dolsem Dynamoose has 0 control over AWS DynamoDB Update Expressions. Although Dynamoose might do work before and after to manipulate the request and improve ease of use, at the end of the day we are limited to what AWS DynamoDB offers. Due to this, I'm slightly confused about what you mean by `I suggest updating $ADD to support this and adding $REMOVE as an opposite of $ADD.`. We can't change how DynamoDB works itself.

In terms of `$DELETE also deletes a counter instead of decrementing it`, that is the intended behavior as the [documentation indicates](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html).

Finally in terms of pull requests, I'm always happy to review any pull requests submitted. Doesn't guarantee that it'll be merged in tho. In this case if you have better ideas of how to handle it, that'd be great. But please keep in mind the limitations and boundaries that DynamoDB has.

**Comment by fishcharlie** [comment] 2018-07-30 17:58
I'm closing this issue for now, and might reopen depending on OPs reply.

**Comment by dolsem** [comment] 2018-07-30 22:14
Sorry for not being clear enough. It was my understanding that update command syntax does not directly correspond (and is not meant to) to that of Update Expressions. In UE there are 4 types: `SET`, `REMOVE`, `ADD` and `DELETE`. Note that current `$DELETE` behavior corresponds to `REMOVE` in UE, and `DELETE` is used to "to remove one or more elements from a set", NOT to remove attributes. 

So my point is, if Dynamoose doesn't attempt to replicate UE exactly (which is what I assumed) there's more leeway and `$ADD` can be updated to work with maps - in UE you can add a key-value pair using `SET` instead, as I mentioned above, but we don't have `SET` in Dynamoose. so currently there seems to be no way to modify a map without a read first. If this route is acceptable, then `$REMOVE` might also be added, with my proposed functionality, not the one in UE. 

If I am wrong and the goal is to actually closely follow UE syntax, then instead of `$PUT`, `$ADD` and `$DELETE` there should probably be `$SET`, `$REMOVE`, `$ADD` and `$DELETE` with original UE behavior, i.e. `$REMOVE` removes attributes and `$DELETE` does not (removes elements from a set instead). This is not something that I personally prefer, because it's confusing (`DELETE` is the opposite of `ADD` when working with sets, and `REMOVE` is used to delete attributes. Switching behavior of `DELETE` and `REMOVE` would make more sense conceptually imo, but that's on Amazon). Also `SET`'s behavior is overcomplicated. Please let me know which path Dynamoose is taking then, because I am confused.

P.S. Also note that I use $ to refer to update keywords in Dynamoose and I omit it to refer to original Update Expressions.

**Comment by fishcharlie** [comment] 2018-07-30 22:40
@brandongoode Thoughts on this?

**Comment by dolsem** [comment] 2018-08-01 08:03
@fishcharlie I can only speak from my point of view, and personally I come from using MongoDB and Mongoose. Recently I decided to transfer my database to Dynamo, and one of the reasons I chose Dynamoose is because originally I was hoping for a seamless transition that wouldn't require many changes to the codebase (which is, I guess, how Dynamoose positions itself, or at least the way I interpreted it). As I can see now, this was unrealistic, because the underlying structure of DynamoDB is different, and the details of the underlying structure matter a lot. The main problem with my transition was Dynamo's documentation, which is often unnecessarily cryptic and is not well organized. The fact that there was some confusion on your part (as far as I understand) about some aspects of update expressions speaks volumes about their documentation, since you've definitely spent way more time with it than me.

So in my opinion what ultimately makes any transition smooth is good documentation with clear explanations and clear examples. It's also helpful to list known limitations in documentation as well, otherwise people will spend time figuring out how to do something that might not yet be implemented (e.g. updating map attributes without first reading them from the database). I think there's still some work to do on that part in Dynamoose. 

I also think that a good API should strive to be as self-explanatory as possible. This is not always the case with Dynamo API (choice between `$REMOVE` and `$DELETE`, or `$SET` and `$ADD` is not obvious, also consider the fact that you add an element to a **set** with `$ADD` and to a map with `$SET` - plenty of room for confusion, and potentially bad/wrong code). Provided there's good documentation, minor differences in API are permissible in my view, if they lead to less code and less confusion.

Again, I want to emphasize that I don't have any prior experience with DynamoDB, so you might want to take my words with a grain of salt.

**Comment by brandongoode** [comment] 2018-09-20 03:12
The issue is how DynamoDB expects the remove names based on indexes. 

Below is the AWS doc:

---

Removing Elements From a List
You can use REMOVE to delete individual elements from a list.

Example

In Appending Elements To a List, we modified a list attribute (RelatedItems) so that it contained five elements:

[0]—Chisel

[1]—Hammer

[2]—Nails

[3]—Screwdriver

[4]—Hacksaw

The following AWS CLI example deletes Hammer and Nails from the list.

```
aws dynamodb update-item \
    --table-name ProductCatalog \
    --key '{"Id":{"N":"789"}}' \
    --update-expression "REMOVE RelatedItems[1], RelatedItems[2]" \
    --return-values ALL_NEW
```

After removing Hammer and Nails, the remaining elements are shifted. The list now contains the following:

[0]—Chisel

[1]—Screwdriver

[2]—Hacksaw

---

This means the name has to contain the index. We would need to modify the remove statmeents to include the indexes: https://github.com/dynamoosejs/dynamoose/blob/d23d4650be1a0fd977cacde768fa7130bdfc61bf/lib/Model.js#L690-L703

Then the code would be something like:

```
Test.update(
  { id: 1 },
  { $DELETE:
    { myList: [0, 1] } 
  }
);
```

**Comment by dolsem** [comment] 2018-10-09 17:05
Okay, makes sense! And what are you thoughts, @brandongoode, on extending that functionality to maps? (I.e. using $ADD and $DELETE to add and delete entries in a map.) I haven't tested it since I posted my issue, but if I'm not mistaken, Dynamoose still doesn't support that yet.

**Comment by q-ode** [comment] 2019-01-10 15:00
What's the status of this please @fishcharlie ?

**Comment by fishcharlie** [comment] 2019-01-10 16:12
@q-ode No updates. Looks like @dolsem asked @brandongoode a question that hasn't gotten a reply. If anyone knows more about this than I do that'd be awesome. But I don't have much insight into this. I don't think it's something that DynamoDB supports.

**Comment by q-ode** [comment] 2019-01-10 21:58
@fishcharlie it actually is, DynamoDB has `REMOVE` and `DELETE`.

The `DELETE` in this library does what `REMOVE` is supposed to do in DynamoDB, hence instead of allowing you remove elements in a Set it removes the entire field.

What I've done in my current project for now is to write an update expressing and use the AWS SDK to run it directly for that part of my project.

**Comment by willowHR** [comment] 2019-02-17 14:25
Wondering if there's any thoughts on this? With the recent addition of list_append it would be great to be able to remove an item from a list (Or is there a known workaround?)

Currently i'm pulling the list - filtering it and then updating the object, but this is dangerous when two removes come in together, only the second gets deleted since the original list is being pulled both times.

Im left with no safe way to remove items from list.

**Comment by allesklarbeidir** [comment] 2019-04-12 20:05
> @fishcharlie it actually is, DynamoDB has `REMOVE` and `DELETE`.
> 
> The `DELETE` in this library does what `REMOVE` is supposed to do in DynamoDB, hence instead of allowing you remove elements in a Set it removes the entire field.
> 
> What I've done in my current project for now is to write an update expressing and use the AWS SDK to run it directly for that part of my project.

Yes, the problem here is, that the dynamoose library does not differentiate between these two commands and a $DELETE in dynamoose actually sends a "REMOVE"-Command to aws dynamodb.

Furthermore, REMOVE can either delete a whole attribute from an item OR remove an item from a LIST (not SET (!)). Since Arrays are saved as SET-Types when using dynamoose, there is no hope for the $DELETE operation in this library to remove an item from an Array. Even if one explicitly uses the LIST type, the REMOVE operation for a single item is not implemented.

To correct the behavior of this library we need to implement $REMOVE and $DELETE according to the AWS Docs. I think I might be able to submit a PR after some more research but any help would be  appreciated. I wonder why this hasn't got a priority for implementation yet. I don't think it's hard to do and without it the library is useless in some critical use-cases.

**Comment by fishcharlie** [comment] 2019-06-27 04:46
I FINALLY got around to looking at this further. I think I'm in FULL support of this issue after taking some time to dig into it and the DynamoDB documentation. I have been playing around with the code base and trying to understand this on a deeper level as well.

I'm trying my hardest for now to build a solution that will not be considered a breaking change. That being said, I don't know if it's going to be possible.

My biggest concern with my solution is that if you are trying to remove a property and aren't passing in `null`, this is for sure a breaking change. The documentation (https://dynamoosejs.com/api/model/#modelupdatekey-update-options-callback) says to use `null`. But I'm not sure if it's explicit enough to be clear.

Also we have a test called `Update $DELETE with saveUnknown enabled` that doesn't use `null` where it should be. Which is kinda encouraging bad use of it.

Below you can find an attachment of my solution I tried.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/860375/60234919-3d59f280-9863-11e9-859b-6823cf18545d.png">

I have not committed this due to the fact that I'm not sure if it's a breaking change, and I'm not sure if we should go forward with this solution.

---

What are everyone's thoughts on this? If we decide my solution above should be considered a breaking change (which is what I'm thinking it is), then I'm more for doing a larger breaking change that adds a `$REMOVE` property, and completely changes the behavior of `$DELETE`. Sadly, I'm not sure if I'm gonna have time to do that larger change effort (but it looks like @CodeBanBan made a commit on a branch to do that large change tho, if @CodeBanBan is willing to submit a PR for it).

---

I know everyone is eager to get this support added, so any help with PRs and getting this across the finish line would be much appreciated.

**Comment by dolsem** [comment] 2019-06-27 12:44
@fishcharlie I agree that it makes most sense to do the larger change if the behavior of the update expressions will be changed anyway. Doesn't look like there's a way to completely align functionality with DynamoDB docs without breaking changes.

One option I can think of that avoids breaking code is to deprecate `$ADD`, `$REMOVE` and `$DELETE` completely and throw a warning, and perhaps plan to remove them in version 2.0.0. Keys with new behavior can be named slightly differently, perhaps `SET, ADD, REMOVE, DELETE`, or `$set, $add, $remove, $delete`. The first option might have issues when key and update expression are supplied inside of the same object as a single argument, though I've never seen much use in making it a single argument, and wouldn't mind for that to be deprecated as well.

If you choose to go forward with a breaking update though, I think it's best if it's scheduled for a major version update, like 2.0.0. Moreover, big libraries usually provide documentation on how to convert code to the new version without breaking anything. And generally speaking be as explicit and as in people's faces as possible.

**Comment by fishcharlie** [comment] 2019-06-27 15:00
@dolsem With our new deployment system, if the commits are marked with “breaking change”, it’ll auto deploy as 2.0.0. So 2.0.0 will just have this PR.

I’m gonna review #644 now, if you’d like to as well and we can base it off of that. Looking forward to getting this in!

**Comment by arunabhCronJ** [comment] 2019-08-23 08:23
Any updates on this change?

**Comment by fishcharlie** [comment] 2019-08-25 01:50
@arunabhCronJ Please refer to the open PR #644 for the latest information.

**Comment by plfx** [comment] 2019-11-11 21:52
Seeing that the PR is still open, what exactly is the workaround to removing an item from a set in the meantime? Is there a way to do it atomically (i.e. without modifying and then updating the entire set)

**Comment by dolsem** [comment] 2019-11-14 15:56
@plfx currently $DELETE translates to REMOVE in Dynamoose, and it doesn't let you remove list or set items. You have to either fetch the whole item, update the set and save it, or update it with AWS SDK directly (`dynamoose.ddb().updateItem()`).

**Closed** 2020-02-16 19:38 UTC
Labels: discussion
