### ISSUE TITLE
Using saveUnknown throws an error when trying to save the boolean value false

### ISSUE THREAD

**Issue by pscamman** [dynamoosejs/dynamoose#360] opened 2018-05-18 15:00 UTC
https://github.com/automategreen/dynamoose/blob/0bbae14aa47d6abe70757194a803f70ccbd872dc/lib/Attribute.js#L151-L155
The above if statement triggers on any falsy value. It is reached when saveUnknown is true:
https://github.com/automategreen/dynamoose/blob/0bbae14aa47d6abe70757194a803f70ccbd872dc/lib/Attribute.js#L19-L21

Unless I'm missing something, saving false (and null even) should be an option here, so this looks like unintended behavior to me.

This wasn't a problem back in 0.8.6.

**Comment by fishcharlie** [comment] 2018-05-18 15:28
@pscamman That does sound like unintended behavior. It looks like it has to do with PR #240. I'm not quite sure how to fix this currently. Any tips would be awesome. Otherwise I'll try to get around to taking a look at this soon.

**Comment by pscamman** [comment] 2018-05-18 15:38
@fishcharlie Cool. If I find some extra time I'll see about taking a deeper look myself as well.

**Comment by ecwyne** [comment] 2018-06-11 15:56
It seems to me that this is fixed if https://github.com/automategreen/dynamoose/blob/master/lib/Attribute.js#L154 is removed entirely.

This enables saving `false`, `''`, and `0`

The only other "falsey" values are `null`, `undefined`, and `NaN`.

`null` is a specific [type](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html) in dynamo
`undefined` should probably just be ignored (not saved)
(Not sure what to do with `NaN`)

**Comment by ecwyne** [comment] 2018-06-11 16:02
See PR #363 for my proposed fix

**Comment by ecwyne** [comment] 2018-06-11 16:49
@fishcharlie is right, there is already a PR that addresses this (#336)

You mentioned including this fix in `0.9`, is there any sense of how soon that will be? (This bug is preventing me from moving forward)

Thanks so much for the awesome library! It makes working with dynamo SO much more enjoyable!

**Comment by fishcharlie** [comment] 2018-06-11 17:05
@ecwyne I'm currently waiting to hear back from @brandongoode. Currently although I have quite a bit of access on this project, I do not have the ability to publish new versions on NPM. I'm going to try to work with @brandongoode to discuss ways to keep this project alive. If that doesn't happen, at some point I will consider creating a new version of this repo (fork) to ensure it gets maintained.

I promise this project will be continued to be maintained somehow for the foreseeable future. If it means me (and my company) taking over a forked version to ensure it continues to be maintained, I promise I will work as hard as I can to ensure this project gets maintained.

That being said I believe there will continue to be a period of time right now where this project is not as active as I would like, while we figure out what is going to happen.

**Comment by fishcharlie** [comment] 2018-06-11 17:29
@ecwyne Let me work on that now. I'll probably just work on merging stuff into master. It would be awesome if you'd be willing to post some comments in the active PRs and review the code to make sure it's ok to be merged in. The more code reviews the better! haha.

**Comment by fishcharlie** [comment] 2018-06-11 17:36
@ecwyne Ok well just leaving comments if it looks good or bad that would be awesome! I'll try to get around to this ASAP.

**Comment by pscamman** [comment] 2018-06-11 18:48
> This enables saving false, '', and 0

@ecwyne Just want to point out: Saving '' causes an error in DynamoDB, aside from anything Dynamoose does.

**Comment by pkonneker** [comment] 2018-10-23 05:50
Looks like the pr referenced here was merged. So can probably close this.

**Closed** 2018-10-23 15:02 UTC
Labels: bug
