### ISSUE TITLE
batchPut with UnprocessedItems

### ISSUE THREAD

**Issue by jongnam** [dynamoosejs/dynamoose#91] opened 2016-12-30 18:28 UTC
Can dynamoose automatically retry `batchPut` until it does not have any`UnprocessedItems`? This feature will let an app simply call `batchPut()` and presume it will retry put operations until every data is being saved.

After the call of dynamoose's `model.batchPut()`, it returns `UnprocessedItems` along with the data itself. the `UnprocessedItems` are the data that DynamoDB could not save due to various reasons such as insufficiently-provisioned write capacity. But the returned `UnprocessedItems` itself is not dynamoose Model object; in fact it is aws-sdk object format. So what I had to do was to use aws-sdk's dynamo.batchWriteItem explicitly. 

Here is the example code:

```
module.exports.batchPut = function(modelName, items, callback) {
    var model = dynamoose.model(modelName);
    model.batchPut(items, function(err, data) {
        if (err || isEmptyObject(data.UnprocessedItems)) {
            callback(err, data);
        } else  {
            const table = Object.keys(data.UnprocessedItems)[0];
            var items = _.flatten(data.UnprocessedItems[table]);
            batchPutItems(table, items, callback);
        }
    });
};

function batchPutItems(table, items, callback) {

    if (items.length === 0) {
        callback(null, null);
        return;
    }

    console.log('Saving remaining %d items of %s...', items.length, table);

    async.map(groupItems(items), function(items, cb) {
        var params = { RequestItems: { } };
        params.RequestItems[table] = items;
        dynamo.batchWriteItem(params, function(err, data) {
            if (err) {
                logger.debug(err);
                cb(err, []);
            } else {
                var remained = data.UnprocessedItems[table];
                if (isUndefined(remained)) cb(null, []);
                else cb(null, remained);
            }
        });
    }, function(err, results) {
        var remained = _.flatten(results);
        if (remained.length === 0) {
            callback(null, null);
        } else {
            batchPutItems(table, remained, callback);
        }
    });
}
```

**Comment by brandongoode** [comment] 2016-12-31 13:45
I agree.

Need to be careful not to loop on valid failures. 

I'm thinking of adding three options for the batch operations:  `retry`, `retryCount` and `initialDelay`.

`retry` if true would retry any UnprocessedItems. Default: false -- preserve current behavior
`retryCount` would limit how many time it attempts write the data. Default: 10
`initialDelay` would  be the first delay in milliseconds for the exponential back off.  Default: 50


The default values of `retryCount` and `initialDelay` are based on Amazons recommendations: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html#Programming.Errors.BatchOperations

**Comment by jongnam** [comment] 2017-01-03 20:10
Glad to hear from you so quickly! Also would be great if this enhancement be applied to the `batchDelete()` as well.

**Comment by doprdele** [comment] 2019-03-20 11:31
Was this ever committed?

**Comment by MattJones** [comment] 2019-08-01 20:00
I'm looking at the source code for `Model#batchPut` on 1.10.0 (https://github.com/dynamoosejs/dynamoose/blob/v1.10.0/lib/Model.js#L1494) and unless I'm misreading it (which is definitely possible) it looks like this never was committed. Am I wrong? If not, is there a suggested workaround within dynamoose without having to use the aws sdk directly?

**Comment by fishcharlie** [comment] 2019-08-01 20:11
@doprdele Not sure what you mean by `Was this ever committed?`.

This work was never done, hence why the issue is still open. Feel free to submit a PR to add this functionality.

**Comment by MattJones** [comment] 2019-08-19 16:43
I put together my own version of a fix for this issue. The `safeBatchPut` default function takes a dynamoose model and an array of items to put. It automatically retries any failed items. It's definitely not solid enough to go into a PR into dynamoose but it might be helpful for anyone else who runs into this issue 😃 .

Caveats:
- Only tested on batchPut, not batch update or batch delete.
- I made my own code for turning the raw dynamoDB unprocessedItems response back into an array that can be handed to dynamoose. I've only tested it on the types for our use case (number, string, date, and boolean).
- Backoff before retrying a batchPut is constant, unlike the exponential backoff recommended by AWS.

```
import _ from 'lodash';

const constants = {
  BATCH_WRITE_MAX_TRIES: process.env.BATCH_WRITE_MAX_TRIES || 30,
  ITEMS_PER_CHUNK: process.env.ITEMS_PER_CHUNK || 2000,
  RETRY_SLEEP_TIME: process.env.RETRY_SLEEP_TIME || 1000,
};

async function sleep(milliseconds) {
  return new Promise(resolve => setTimeout(resolve, milliseconds));
}

function transformRawUnprocessedItem(rawItemObject) {
  return _.transform(rawItemObject, (accumulator, rawValue, key) => {
    // rawValue is expected to have a format like {"N": "1564694609754"}
    const type = _.keys(rawValue)[0]; // Will be "N", "S", "BOOL", etc.
    if (!_.includes(['N', 'S', 'BOOL'], type)) {
      console.warn(`transformRawUnprocessedItem is untested for dynamo type "${type}"`);
    }
    const untypedValue = _.values(rawValue)[0];
    const value = (type === 'N') ? parseInt(untypedValue, 10) : untypedValue;
    if (_.isNaN(value) && type === 'N') {
      throw new Error(`couldn't parse value to integer for key ${key}`);
    }
    accumulator[key] = value;
  }, {});
}

function sanityCheck(rawUnprocessedItems, unprocessedItems) {
  // Double-check just in case AWS or dynamoose changes their UnprocessedItems return structure.
  if (_.isEmpty(unprocessedItems) && !_.isEmpty(rawUnprocessedItems)) {
    throw new Error('UnprocessedItems could not be parsed!');
  }
}

/**
 * Takes the UnprocessedItems object returned by dynamoose::model#batchPut and converts it
 * back to events that can be resubmitted to batchPut
 *
 * @param {object} rawUnprocessedItems - The UnprocessedItems value of the batchPut response object
 * @return {array}
 */
export function transformRawUnprocessedItems(rawUnprocessedItems) {
  if (_.isEmpty(rawUnprocessedItems)) { return []; }

  return _
    .chain(rawUnprocessedItems)
    .values()
    .flattenDeep()
    .map(item => item.PutRequest.Item)
    .map(item => transformRawUnprocessedItem(item))
    .value();
}

// Batch-puts items to DynamoDB, and returns a list of items that failed to process.
async function batchPutItems(model, items) {
  console.info(`running batchPutItems on ${items.length} items.`);
  return new Promise((resolve, reject) => {
    model.batchPut(items, (err, response) => {
      if (err) {
        console.error(`Failed batchPut. error: ${err}`);
        reject(err);
      }
      const rawUnprocessedItems = response.UnprocessedItems;
      const unprocessedItems = transformRawUnprocessedItems(rawUnprocessedItems);
      sanityCheck(rawUnprocessedItems, unprocessedItems);
      resolve(unprocessedItems);
    });
  });
}

/**
 * Bulk writes to a DynamoDb table and safely retries any failed writes
 *
 * @param {dynamoose.model} model - The dynamoose model
 * @param {array} items - The objects to be written to DynamoDB
 * @return {void}
 */
async function batchPutItemsWithRetry(model, items) {
  let attempt = 1;
  let itemsToSave = items;
  while (!_.isEmpty(itemsToSave)) {
    if (attempt > constants.BATCH_WRITE_MAX_TRIES) {
      throw new Error(`Batch write exceeded maximum ${constants.BATCH_WRITE_MAX_TRIES} attempts`);
    }

    // eslint-disable-next-line no-await-in-loop
    const unprocessedItems = await batchPutItems(model, itemsToSave);
    if (_.isEmpty(unprocessedItems)) {
      return;
    }

    console.info(`Found ${unprocessedItems.length} unprocessed items after attempt ${attempt}.`);
    await sleep(constants.RETRY_SLEEP_TIME); // eslint-disable-line no-await-in-loop
    // Note: The AWS Docs recommend using an exponential backoff, but we've found that in our
    //   use case it doesn't seem to make a difference.
    attempt += 1;
    itemsToSave = unprocessedItems;
  }
}

/**
 * Bulk writes to a DynamoDb table and safely retries any failed writes. Requests are broken up
 * into chunks and submitted serially to avoid hitting the lambda's limit on open connections to
 * DynamoDB, since dynamoose holds multiple open connections for each batchPut.
 *
 * @param {dynamoose.model} model - The dynamoose model
 * @param {array} items - The objects to be written to DynamoDB
 * @return {void}
 */
export default async (model, items) => {
  console.info(`Running with these constants: ${JSON.stringify(constants)}`);

  const chunks = _.chunk(items, constants.ITEMS_PER_CHUNK);

  for (let i = 0; i < chunks.length; i += 1) {
    console.info(`Running chunk ${i + 1} out of ${chunks.length}`);
    // eslint-disable-next-line no-await-in-loop
    await batchPutItemsWithRetry(model, chunks[i]);
  }
};
```

**Closed** 2020-02-16 19:38 UTC
Labels: enhancement, help wanted
