### ISSUE TITLE
dynamoose scan all results till recursively

### ISSUE THREAD

**Issue by venkataprasadmanne** [dynamoosejs/dynamoose#435] opened 2018-10-08 13:35 UTC
currently I have a requirement to dump all the table entries when this particular api is called and I tried below  but it seems all entries do not show up,i checked the documentation and  it's little confusing.

```
Dog.scan().exec(function (err, dogs) {
 //send all dogs
});
```

docs say that we need to make recursive calls till all the entries are retrieved based on the value of lastKey,that doesnt seem very effective solution to me to make so many recursive calls

scan.all also does seem to solve this problem,could someone please suggest the syntax?

```
Dog.scan().all(function (err, dogs) {
 //send all dogs
});

```
will this work?

**Comment by fishcharlie** [comment] 2018-10-08 15:16
@venkataprasadmanne If you are not seeing all the entries then yes there is probably a `lastKey` specified, and you need to make recursive calls to get all the data. There are a lot of things to think about here, but let me first answer your question before giving you a lot of things I **highly** recommend you think about.

The following syntax will get all the items. By default there is a delay of 1 second between recursive scans. See the documentation at [`Scan.all()`](https://dynamoosejs.com/api#scanalldelay-max).

```
Dog.scan().all().exec(function (err, dogs) {
 //send all dogs
});
```

Therefor this solution will make recursive calls, and will basically do exactly what you were talking about, except automatically with a delay. Therefor your notion of it being not very effective still applies in this situation.

The problem is, DynamoDB doesn't return the `lastKey` to you until you get the response from the call. And DynamoDB has limits for how much data can be returned.

You can look into something like [`Scan.parallel()`](https://dynamoosejs.com/api#scanparalleltotalsegments) to try to speed up this process and scan in parallel. That option will take up a LOT of capacity tho, so keep that in mind.

This really comes down to how much data you have, and how fast you want to get it. There isn't really any other options that I'm aware of besides what I have just mentioned. If you have millions of records and a ton of data, none of these options will be SUPER efficient.

I think a question you have to ask yourself, is why you are needing to get all the data out of this table? And if DynamoDB is the best solution for your use case.

I would also highly encourage you to rethink why you need to get this data out on an API call. How are you going to prevent DDOS attacks? What if someone hits that API over and over? Your system will grind to a halt if that happens. Scalability and cost becomes a major issue for this.

One example I would encourage you to think about, is a lot of sites are now allowing users to download all of their data. These services almost always send you an email when it's complete, and that process can take multiple hours. These services also tend to impose limits on how often you can request that data. Both of these options I'm assuming are in place to try to prevent attacks and prevent their databases from being overloaded. Those are both options I would highly consider doing, to ensure that you aren't overloading your database.

Finally these services are probably adding some type of query to only get the data for your user instead of getting all the data in their table. Which makes it far more efficient than what you are trying to do.

So, just as a summary:

1. Think about if DynamoDB is really the best option for your use case, and why you are needing to get all the data from the table
2. Write defensive code to ensure that attackers can't attack your database layer
3. Ensure that you have enough capacity on your table to preform this operation
4. Consider using `Scan.all` (or manually making recursive calls with the `lastKey`) and/or `Scan.parallel` for the code side of things

---

I hope this helps! I'm going to be closing this issue for now, but please feel free to comment or [contact me](https://charlie.fish/contact) if something didn't make sense, you have follow up questions or anything like that.

Good luck in your future coding adventures!

**Closed by fishcharlie** 2018-10-08 15:16 UTC

**Comment by venkataprasadmanne** [comment] 2018-10-09 11:46
@fishcharlie amazing! Thank you,i guess scan.all works for me as this feature is available only for admin users, i will analyse on scenarios you provided.
