### ISSUE TITLE
query doesn't work with index 

### ISSUE THREAD

**Issue by lbayarkhuu** [dynamoosejs/dynamoose#552] opened 2019-01-31 08:01 UTC
### Code sample:
```
User.query(label).eq(item).exec(async (error, user) => {})
```

#### Schema
```
const dynamoose = require('dynamoose')

const { prefix } = process.env

const User = new dynamoose.Schema({
  fbId: {
    type: String,
    default: "",
  },
  walletId: {
    type: String,
    index: {
      global: true,
      name: 'walletId-index',
    },
  },
  userId: {
    type: String,
    index: {
      global: true,
      name: 'userId-index',
    },
  }
}, {
  timestamps: {
    updatedAt: 'updatedAt',
    createdAt: 'createdAt'
  }
})

module.exports = dynamoose.model(`User`, User, {update: true, create: true});

```
#### Error

TypeError: Cannot read property 'toDynamo' of undefined
    at Query.exec (/home/..../backend/node_modules/dynamoose/lib/Query.js:105:35)
    at values.map.item (/home/bx/Projects/fb-project/fb-extension/backend/query.js:19:32)
    at Array.map (<anonymous>)
    at getUsers (/home/bx/Projects/fb-project/fb-extension/backend/query.js:18:10)
    at Object.<anonymous> (/home/bx/Projects/fb-project/fb-extension/backend/query.js:28:1)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)

**Comment by fishcharlie** [comment] 2019-02-04 01:57
Closing this issue due to not enough information to reproduce. Might reopen in the future depending on OP response.

**Closed by fishcharlie** 2019-02-04 01:57 UTC
