### ISSUE TITLE
Request - Multi-Tenant Invoke of DynamoDB via STS

### ISSUE THREAD

**Issue by judahb** [dynamoosejs/dynamoose#279] opened 2018-01-22 21:54 UTC
Hi ,

I am requesting that you allow each dynamoose request to be invoked at runtime with STS credentials obtained from AWS, rather than requiring a role or static credentials. The reason, is because allowing STS credentials to be used allows one to integrate multi-tenant or custom access via fine grained IAM policy to dynamodb requests as defined by the IAM policy and role that a user has within their STS Credentials. The primary use case is for integration to Cognito User Pools or another OpenID Provider allowing the credentials from STS to flow directly into dynamoose exposing access at the AWS level rather than at the application level. Let me know if this makes sense.

**Comment by fishcharlie** [comment] 2018-04-03 23:09
If anyone would like to PR for this, I would be happy to take a look at it and get it merged in.

**Comment by judahb** [comment] 2018-04-14 01:50
https://github.com/automategreen/dynamoose/blob/master/lib/index.js

On this file, when leveraging the constructor for AWS.Dynamodb can you allow for STS credentials as a parameters, rather than instantiating with the credentials of the role at run time? Maybe by keeping the current approach as default, but where a configuration can be set in dynamoose allowing one to pass STS credentials. Use case here is to pass the STS Credentials obtained from getCredentials() method which allows Cognito to obtain STS creds from an Access or ID token.

**Comment by fishcharlie** [comment] 2018-04-15 18:26
@judahb That sounds good to me. I haven't worked with STS credentials before tho, so it will probably be a while before I get around to working on this. If you would like to make a PR I would be happy to review it and try to get it merged in.

**Comment by judahb** [comment] 2018-04-16 16:41
This should be straight-forward. Simply pass the attributes this way. Note, that these should have the ability for one to pass as an event, not simply storing the access and secret in-memory. Let me know if this makes sense. As an example, if you were to create an application with dynamoose in lambda, one can leverage getCredentials from Cognito to convert an ID/Access (JWT) Token into STS Creds which include the Session Token, Session Duration, Access Key, and Secret Access Key. These would then be passed per user into the constructor.

        var dynamodb = new AWS.DynamoDB({
            apiVersion: '2012-08-10',
            sessionToken: <SESSION_TOKEN>,
            accessKeyId: <ACCESS_KEY_ID>,
            secretAccessKey: <SECRET_KEY>,
            region: <REGION_ID>
        });

**Comment by fishcharlie** [comment] 2018-12-05 06:38
@judahb I think this might be possible with the [`dynamoose.setDDB`](https://dynamoosejs.com/api#dynamoosesetddb) method. If not let me know and I can reopen this issue.

**Closed by fishcharlie** 2018-12-05 06:38 UTC
Labels: enhancement, help wanted

**Comment by set-killer** [comment] 2020-02-05 13:03
Hi folks, i think this issue should be reopened. 
The problem is that `dynamoose` is used as singleton. For example if there are 2 requests running in parallel at the same time, the first request will attach an AWS Dynamodb instance to the instance of dynamoose, then the second request will override the previously attached DynamoDB instance.

The example looks like this:
`request start() -> setDDB(new AWS.dynamodb) -> wait for 10 sec. -> make dynamoose scan()`
And at the same time another requests appears:
`request start() -> setDDB(new AWS.dynamodb) -> make dynamoose scan()`

Basically the second request is overriding the internal dynamodb instance of dynamoose and as a result the both scans will be made with the same credentials.

In my opinion the best approach would be to have a constructor that uses an AWS DynamoDB object like:

```
    var dynamodb = new AWS.DynamoDB({
        apiVersion: '2012-08-10',
        sessionToken: <SESSION_TOKEN>,
        accessKeyId: <ACCESS_KEY_ID>,
        secretAccessKey: <SECRET_KEY>,
        region: <REGION_ID>
    });

    var dynamooseInstance = new dynamoose(dynamodb);
```
or
```
    var dynamooseInstance = dynamoose.setDDB(dynamodb);
```

**Comment by fishcharlie** [comment] 2020-02-05 16:40
@set-killer What is the use case here? Don't think Mongoose supports this, and I'm struggling to think of a justifiable use case for why this should be implemented/supported.

**Comment by set-killer** [comment] 2020-02-06 09:23
@fishcharlie It's the same use case - Multi tenant environment. 
Imagine having an authentication from AWS Cognito, After the user authenticates successfully the Cognito provides accessKey and secretKey for that user. After that all dynamodb requests should be made with that accessKey and secretKey. Additionally on every dynamodb table there is an 'Access Control' option. As far as i understand with the access control options on the table it is possible to restrict the access over some of the records for this user specifically. For example 'my current user' has access only to the records that have hash key 'tenant-unique-uuid'  or only to a group of hash keys that starts with 'tenant-uuid-*'.
All this user sessions, access keys and secret keys are stored and managed by Cognito. With this approach the dynamodb credentials are part of the user's state, not the application state.

**Comment by fishcharlie** [comment] 2020-02-06 22:17
@set-killer Thanks for the feedback. This likely won't be implemented anytime soon. Therefore since it's not really on the priority list, and due to some of the restructuring going on with the v2.0 rewrite, I'm going to keep this issue closed for now.

After the v2.0 rewrite is done, feel free to help work on a PR to implement this tho!
