### ISSUE TITLE
Scan returns no items

### ISSUE THREAD

**Issue by sabreenakp** [dynamoosejs/dynamoose#553] opened 2019-01-31 12:37 UTC
### Summary:

I tried to scan items with conditions.but didn't return any items even if the matching item present in the table

### Code sample:

userchema.statics.finduser = function (user, cb) {
    this.scan({ email: user.email, activeFlag: true }, function (err, res) {
        cb(err, res);
    });
}

dynamoose.model('user', userSchema);

#### Schema
```
var userSchema = new Schema({
    mob_value: {
        type: String,
        hashKey: true
    },
    id_value: {
        type: String,
        rangeKey: true
    },
    email: {
        type: String,
        index: true
    },
    fam: {
        type: String
    },
    pwd: {
        type: String
    },
    dob: {
        type: String
    },
    access: {
        type: Array,
        required: true
    },
    site: {
        type: String
    },
    code: {
        type: String,
        default: shortid.generate
    },
    wife: {
        type: Array
    },
    child: {
        type: Array
    },
    father: {
        type: Object
    },
    data1: {
        type: String
    },
    pictue: {
        type: String
    },
    pArr: {
        type: Array
    },
    eArr: {
        type: Array
    },
    lstAtt: {
        type: String
    },
    lstPgm: {
        type: String
    },
    lstLog: {
        type: String
    },
    activeFlag: {
        type: Boolean,
        default: true
    },
    crDate: {
        type: String,
        default: datetime
    }
}, {
        throughput: { read: 15, write: 5 }
    }, {
        create: true, // Create table in DB, if it does not exist,
        update: false, // Update remote indexes if they do not match local index structure
        waitForActive: true, // Wait for table to be created before trying to use it
        waitForActiveTimeout: 180000 // wait 3 minutes for table to activate
    });
// Code here
```

#### Model
```
// Code here
```

#### General
```
// Code here
```

### Current output and behavior:

[ lastKey: undefined,
  count: 0,
  scannedCount: 995,
  timesScanned: 1 ]

### Expected output and behavior:

Expecting an user return with matching email

### Environment:

Operating System: Ubunutu
Operating System Version: 14.04
Node.js version (`node -v`): v9.3.0
NPM version: (`npm -v`): 5.5.1
Dynamoose version:  "dynamoose": "^1.4.0",

**Comment by fishcharlie** [comment] 2019-01-31 16:24
Closing this issue due to not enough information to reproduce.

Is the `userchema.statics.finduser` even being called? What is `user` set to? Do you even have items in you database that match that email address you are trying to pass in?

Also please be sure to fill out the entire issue template next time.

**Closed by fishcharlie** 2019-01-31 16:24 UTC

**Comment by sabreenakp** [comment] 2019-02-01 06:40
Yes , userchema.statics.finduser is called and email is passed to the function, Matching item is present in the table

function finduser(user, cb) {
    userModel.finduser(user, function (err, response) {
        if (err) {
            cb(err);
        } else {
            cb(null, response);
        }
    });
}

the above function is the one calls userschema function.

user argument is an object which contains email key and its value.

**Comment by sabreenakp** [comment] 2019-02-01 07:41
Also, another observation is dynamoose version 0.7.0 returns the item but 1.4.0 not

Is anything missing from my end for the latest version? Any help will be highly appreciated.

**Comment by fishcharlie** [comment] 2019-02-01 15:38
@sabreenakp Still not enough information to reproduce. Please create a PR with a failing test case replicating this issue, and I will look into trying to debug it.

You can also run `export DEBUG=dynamoose*` to get more logs about what Dynamoose is doing behind the scenes.

**Comment by soliveira-vouga** [comment] 2019-08-21 16:47
It's possible your records stored the boolean as a string. Since Dynamoose 1.x (I believe) the option `useNativeBooleans` is set to true. I've noticed that this means any records that previously stored a boolean value as a string will not be found if you're trying to scan/query it as a boolean.

When I set `useNativeBooleans` to false in my schema, my scan returned the results I expected.

So you either need to migrate your data to use BOOL or disable useNativeBooleans

@fishcharlie is this expected behaviour? Even if I define a boolean in my schema and the record was saved as a string, should the scan/query methods still not know how to deal with `{ S: 'true' }` and `{ S: 'false' }`?
